#pragma once

enum Categoria { IDENTIFICADOR = 255, OP_COMP, ASIGNAR, NUMERO, ERROR, END,
        OP_SUMA, OP_RESTA, OP_MUL, OP_DIV, COMA, PAR_INICIO, PAR_FINAL,
        CORCH_INICIO, CORCH_FINAL, LLAVES_INICIO, LLAVES_FINAL, COM,
        PALABRA_RESERVADA};

