#pragma once

enum Categoria { IDENTIFICADOR = 255, RELOP, ASSIGN, NUMERO, ERROR, END, 
    SUM_OP, MINUS_OP, MUL_OP, DIV_OP, COLON, PAR_BEGIN, PAR_END, 
    SQR_BRACKET_BEGIN, SQR_BRACKET_END, CUR_BRACKET_BEGIN, CUR_BRACKET_END, COM,
    RESERV_WORD};
